# -*- coding: utf-8 -*-
"""Mobile App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOIVJYdJUZ8ORwDhEChw264f6r_zy7sy
"""

import flet as ft
import requests
import base64
import json

# --- CONFIGURATION ---
# !!! แก้ตรงนี้ให้เป็น IP ของเครื่อง Server ที่รันไฟล์ driver_server.py !!!
# ถ้ารัน Emulator Android ใช้ 10.0.2.2 ได้ แต่ถ้าเครื่องจริงต้องใช้ IP วง LAN (เช่น 192.168.1.xxx)
API_URL = "http://192.168.1.50:9996"

# --- SERVICE (เชื่อมต่อกับ Backend) ---
class DriverService:
    def login(self, username, password):
        try:
            url = f"{API_URL}/api/login"
            resp = requests.post(url, json={"username": username, "password": password}, timeout=5)
            if resp.status_code == 200:
                return True
            return False
        except Exception as e:
            print(f"Login Error: {e}")
            return False

    def get_jobs(self, username):
        try:
            url = f"{API_URL}/api/driver/get_jobs?regis={username}"
            resp = requests.get(url, timeout=5)
            if resp.status_code == 200:
                return resp.json()
            return []
        except Exception as e:
            print(f"Get Jobs Error: {e}")
            return []

    def update_step(self, job_id, step, photo_base64=None, status='Assigned'):
        try:
            url = f"{API_URL}/api/driver/update_step"
            payload = {
                "job_id": job_id,
                "step": step,
                "photo": photo_base64,
                "status": status
            }
            resp = requests.post(url, json=payload, timeout=10)
            return resp.status_code == 200 and resp.json().get("status") == "success"
        except Exception as e:
            print(f"Update Error: {e}")
            return False

service = DriverService()

# --- APP UI ---
def main(page: ft.Page):
    page.title = "Driver App"
    page.theme_mode = ft.ThemeMode.LIGHT
    page.bgcolor = "#f0f8ff"
    page.scroll = "auto"

    # State
    current_user = {"username": None}

    # File Picker (Camera)
    # หมายเหตุ: การเปิดกล้องใน Flet บนมือถือจะใช้ FilePicker เรียก Native Camera
    def on_file_picked(e: ft.FilePickerResultEvent):
        if e.files and len(e.files) > 0:
            file_path = e.files[0].path
            # แปลงไฟล์รูปเป็น Base64 เพื่อส่ง API
            try:
                with open(file_path, "rb") as image_file:
                    encoded_string = base64.b64encode(image_file.read()).decode('utf-8')
                    # format data:image/jpeg;base64,...
                    full_base64 = f"data:image/jpeg;base64,{encoded_string}"

                    # ส่งข้อมูลไป Server (ใช้ตัวแปร global ที่เก็บ state ชั่วคราว)
                    if hasattr(page, 'temp_job_action'):
                        job_id, next_step = page.temp_job_action
                        success = service.update_step(job_id, next_step, full_base64)
                        if success:
                            page.snack_bar = ft.SnackBar(ft.Text("อัปเดตงานสำเร็จ!"), bgcolor="green")
                        else:
                            page.snack_bar = ft.SnackBar(ft.Text("อัปเดตล้มเหลว"), bgcolor="red")
                        page.snack_bar.open = True
                        refresh_jobs_view() # Refresh หน้าจอ
            except Exception as ex:
                print(ex)

    file_picker = ft.FilePicker(on_result=on_file_picked)
    page.overlay.append(file_picker)

    # --- VIEWS & NAVIGATION ---

    def login_view():
        user_input = ft.TextField(label="ทะเบียนรถ (เช่น 1กก-1234)", border_radius=20, filled=True, bgcolor="white")
        pass_input = ft.TextField(label="รหัสผ่าน", password=True, border_radius=20, filled=True, bgcolor="white")
        error_txt = ft.Text("", color="red", visible=False)
        loading = ft.ProgressRing(visible=False)

        def on_login_click(e):
            loading.visible = True
            error_txt.visible = False
            page.update()

            if service.login(user_input.value, pass_input.value):
                current_user["username"] = user_input.value
                page.go("/jobs")
            else:
                loading.visible = False
                error_txt.value = "เข้าสู่ระบบไม่สำเร็จ (เช็คเน็ต หรือ รหัสผ่าน)"
                error_txt.visible = True
                page.update()

        return ft.View(
            "/login",
            [
                ft.Container(
                    content=ft.Column([
                        ft.Icon(ft.icons.DIRECTIONS_CAR, size=80, color="#4682b4"),
                        ft.Text("Driver App", size=30, weight="bold", color="#4682b4"),
                        ft.Divider(height=20, color="transparent"),
                        user_input,
                        pass_input,
                        error_txt,
                        loading,
                        ft.ElevatedButton("เข้าสู่ระบบ", on_click=on_login_click, width=200, bgcolor="#87cefa", color="white")
                    ], horizontal_alignment=ft.CrossAxisAlignment.CENTER),
                    alignment=ft.alignment.center,
                    padding=30
                )
            ],
            vertical_alignment=ft.MainAxisAlignment.CENTER,
            horizontal_alignment=ft.CrossAxisAlignment.CENTER
        )

    def jobs_view():
        jobs_col = ft.Column(scroll="auto", spacing=15)

        def refresh_jobs_view():
            jobs = service.get_jobs(current_user["username"])
            jobs_col.controls.clear()

            if not jobs:
                jobs_col.controls.append(
                    ft.Container(content=ft.Text("ไม่พบงานคงค้าง", size=20, color="grey"), alignment=ft.alignment.center, padding=50)
                )
            else:
                for job in jobs:
                    jobs_col.controls.append(build_job_card(job))
            page.update()

        # ทำให้ refresh_jobs_view เรียกใช้จากข้างนอกได้ (สำหรับ callback กล้อง)
        globals()['refresh_jobs_view'] = refresh_jobs_view

        def build_job_card(job):
            step = job.get('current_step', 0)
            status = job.get('status', 'Assigned')

            btn = None

            # Helper เพื่อเรียกกล้องและจำ state
            def trigger_cam(e, jid, ns):
                page.temp_job_action = (jid, ns)
                file_picker.pick_files(allow_multiple=False, file_type=ft.FilePickerFileType.IMAGE)

            def trigger_close(e, jid):
                if service.update_step(jid, 4, status='Completed'):
                    refresh_jobs_view()

            if status == 'Pending Close':
                btn = ft.ElevatedButton("ยืนยันปิดงาน (Manual)", bgcolor="#ffab91", color="white", width=float("inf"),
                                      on_click=lambda e: trigger_close(e, job['id']))
            elif step == 0:
                btn = ft.ElevatedButton("1. ถ่ายรูปถึงฟาร์ม", icon=ft.icons.CAMERA_ALT, bgcolor="#81d4fa", color="white", width=float("inf"),
                                      on_click=lambda e: trigger_cam(e, job['id'], 1))
            elif step == 1:
                btn = ft.ElevatedButton("2. ถ่ายรูปออกจากฟาร์ม", icon=ft.icons.LOCAL_SHIPPING, bgcolor="#ffcc80", color="white", width=float("inf"),
                                      on_click=lambda e: trigger_cam(e, job['id'], 2))
            elif step == 2:
                btn = ft.ElevatedButton("3. ถ่ายรูปถึงโรงงาน", icon=ft.icons.FACTORY, bgcolor="#a5d6a7", color="white", width=float("inf"),
                                      on_click=lambda e: trigger_cam(e, job['id'], 3))
            elif step == 3:
                btn = ft.ElevatedButton("ยืนยันปิดงาน", icon=ft.icons.CHECK_CIRCLE, bgcolor="#4db6ac", color="white", width=float("inf"),
                                      on_click=lambda e: trigger_close(e, job['id']))

            return ft.Container(
                content=ft.Column([
                    ft.Row([
                        ft.Text(f"Job: {job.get('booking_no')}", weight="bold"),
                        ft.Container(content=ft.Text(status, size=12, color="white"), bgcolor="#0097a7", padding=5, border_radius=5)
                    ], alignment=ft.MainAxisAlignment.SPACE_BETWEEN),
                    ft.Divider(),
                    ft.Text(f"จาก: {job.get('trans_from')}"),
                    ft.Text(f"ถึง: {job.get('trans_to')}"),
                    ft.Text(f"เวลา: {job.get('time_start')} - {job.get('time_end')}", color="grey"),
                    ft.Container(height=10),
                    btn
                ]),
                padding=15, bgcolor="white", border_radius=15,
                shadow=ft.BoxShadow(blur_radius=5, color=ft.colors.with_opacity(0.1, "black"))
            )

        # GPS Status (Dummy - Flet บน PC อาจจะไม่จับ GPS จริง ต้องใช้ Library เสริมบนมือถือ)
        gps_box = ft.Container(
            content=ft.Row([ft.Icon(ft.icons.SATELLITE, color="green"), ft.Text("GPS Active (Sending to Server...)", color="green")]),
            bgcolor="white", padding=10, border_radius=10, margin=ft.margin.only(bottom=10)
        )

        refresh_jobs_view() # Load Data on init

        return ft.View(
            "/jobs",
            [
                ft.AppBar(title=ft.Text(f"Driver: {current_user['username']}"), bgcolor="white", actions=[
                    ft.IconButton(ft.icons.LOGOUT, on_click=lambda e: page.go("/login"))
                ]),
                ft.Container(content=ft.Column([gps_box, jobs_col]), padding=10)
            ],
            bgcolor="#f0f8ff"
        )

    def route_change(route):
        page.views.clear()
        if page.route == "/login":
            page.views.append(login_view())
        elif page.route == "/jobs":
            if not current_user["username"]:
                page.go("/login")
            else:
                page.views.append(jobs_view())
        page.update()

    page.on_route_change = route_change
    page.go("/login")

ft.app(target=main)